services:
  - type: web
    name: books-23it139
    runtime: node
    plan: starter
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 24
      - key: STUDENT_NAME
        value: Tran Van Lam
      - key: STUDENT_ID
        value: 23IT139
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_READ_URI
        sync: false
      - key: MONGODB_WRITE_URI
        sync: false
      - key: MONGODB_SESSION_URI
        sync: false
      - key: WEB_READER_USERNAME
        value: 23IT139_reader
      - key: WEB_READER_PASSWORD_HASH
        sync: false
      - key: WEB_WRITER_USERNAME
        value: 23IT139_writer
      - key: WEB_WRITER_PASSWORD_HASH
        sync: false
